"""paper trading portfolio

Revision ID: 03288f241f54
Revises: 319166c41e7d
Create Date: 2026-08-12 09:40:21.342918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03288f241f54'
down_revision: Union[str, None] = '319166c41e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash_balance >= 0', name='ck_portfolios_cash_non_negative'),
    sa.CheckConstraint('initial_capital > 0', name='ck_portfolios_capital_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_portfolios_user')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_portfolio_positions_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'stock_id', name='uq_portfolio_positions_portfolio_stock')
    )
    op.create_index(op.f('ix_portfolio_positions_portfolio_id'), 'portfolio_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_stock_id'), 'portfolio_positions', ['stock_id'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_source', sa.String(length=16), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("side IN ('buy', 'sell')", name='ck_portfolio_transactions_side'),
    sa.CheckConstraint('quantity > 0', name='ck_portfolio_transactions_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_transactions_executed_at'), 'portfolio_transactions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_portfolio_id'), 'portfolio_transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_stock_id'), 'portfolio_transactions', ['stock_id'], unique=False)
    # ### end Alembic commands ###

    # RLS: cùng cơ chế với watchlists (migration 4440556391f6) —
    # `app.current_user_id` được FastAPI set đầu mỗi transaction trong
    # core/auth.py::get_authed_db. Danh mục chứa tiền và lịch sử giao dịch
    # riêng của từng người nên đây là lớp phòng hờ đáng có, dù lớp chính
    # vẫn là kiểm tra ownership trong routers/portfolio.py.
    #
    # LƯU Ý: RLS chỉ thực sự có hiệu lực khi app kết nối bằng role KHÔNG
    # sở hữu bảng (xem migration 319166c41e7d) — Postgres bỏ qua policy
    # với table owner/superuser.
    op.execute("ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY portfolios_owner_only ON portfolios
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
        WITH CHECK (user_id = current_setting('app.current_user_id', true)::uuid)
        """
    )
    for table in ("portfolio_positions", "portfolio_transactions"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_owner_only ON {table}
            USING (
                portfolio_id IN (
                    SELECT id FROM portfolios
                    WHERE user_id = current_setting('app.current_user_id', true)::uuid
                )
            )
            WITH CHECK (
                portfolio_id IN (
                    SELECT id FROM portfolios
                    WHERE user_id = current_setting('app.current_user_id', true)::uuid
                )
            )
            """
        )

    # Bảng tạo sau migration 319166c41e7d nên không nằm trong GRANT ...
    # ON ALL TABLES của migration đó. ALTER DEFAULT PRIVILEGES ở đó có lo
    # phần này, nhưng chỉ khi migration chạy bằng cùng role đã đặt default
    # privileges — cấp lại tường minh cho chắc, IF EXISTS để không vỡ ở
    # môi trường dev chưa tạo role.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_backend') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON portfolios, portfolio_positions, portfolio_transactions
                    TO app_backend;
                GRANT USAGE, SELECT ON
                    portfolios_id_seq, portfolio_positions_id_seq, portfolio_transactions_id_seq
                    TO app_backend;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS portfolio_transactions_owner_only ON portfolio_transactions")
    op.execute("DROP POLICY IF EXISTS portfolio_positions_owner_only ON portfolio_positions")
    op.execute("DROP POLICY IF EXISTS portfolios_owner_only ON portfolios")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_transactions_stock_id'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_portfolio_id'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_executed_at'), table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_positions_stock_id'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_portfolio_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
