"""initial schema

Revision ID: 4440556391f6
Revises: 
Create Date: 2026-08-06 08:57:54.008042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4440556391f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('prob_up', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('predicted_label', sa.String(length=8), nullable=True),
    sa.Column('actual_label', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'prediction_date', 'model_name', name='uq_ai_predictions_stock_date_model')
    )
    op.create_index(op.f('ix_ai_predictions_stock_id'), 'ai_predictions', ['stock_id'], unique=False)
    op.create_table('data_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sync_log_stock_id'), 'data_sync_log', ['stock_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_price_history_stock_date')
    )
    op.create_index('ix_price_history_stock_date_desc', 'price_history', ['stock_id', sa.text('trade_date DESC')], unique=False)
    op.create_index(op.f('ix_price_history_stock_id'), 'price_history', ['stock_id'], unique=False)
    op.create_table('realtime_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('match_volume', sa.BigInteger(), nullable=True),
    sa.Column('ref_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ceiling_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('floor_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'captured_at', name='uq_realtime_quotes_stock_time')
    )
    op.create_index('ix_realtime_quotes_stock_captured_desc', 'realtime_quotes', ['stock_id', sa.text('captured_at DESC')], unique=False)
    op.create_index(op.f('ix_realtime_quotes_stock_id'), 'realtime_quotes', ['stock_id'], unique=False)
    op.create_table('stock_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('volatility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'score_date', name='uq_stock_scores_stock_date')
    )
    op.create_index(op.f('ix_stock_scores_stock_id'), 'stock_scores', ['stock_id'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ma50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ma200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema12', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema26', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_technical_indicators_stock_date')
    )
    op.create_index('ix_technical_indicators_stock_date_desc', 'technical_indicators', ['stock_id', sa.text('trade_date DESC')], unique=False)
    op.create_index(op.f('ix_technical_indicators_stock_id'), 'technical_indicators', ['stock_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlists_user_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'stock_id', name='uq_watchlist_items_watchlist_stock')
    )
    op.create_index(op.f('ix_watchlist_items_stock_id'), 'watchlist_items', ['stock_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row Level Security cho watchlists/watchlist_items -------------------
    # FastAPI dùng CHUNG một role SQLAlchemy để query (không qua PostgREST),
    # nên policy dựa vào auth.uid() sẽ vô tác dụng (auth.uid() chỉ có giá trị
    # trong context PostgREST/Supabase client, không có trong 1 connection
    # SQLAlchemy thường). Thay vào đó: app/core/auth.py chạy
    # `SET LOCAL app.current_user_id = '<uid>'` đầu mỗi transaction sau khi
    # verify JWT, và policy dưới đây so khớp với giá trị đó. Đây là lớp bảo
    # vệ thứ 2 thật sự có tác dụng — lớp chính vẫn là kiểm tra ownership
    # trong code FastAPI (routers/watchlist.py).
    op.execute("ALTER TABLE watchlists ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY watchlists_owner_only ON watchlists
        USING (user_id = current_setting('app.current_user_id', true)::uuid)
        WITH CHECK (user_id = current_setting('app.current_user_id', true)::uuid)
        """
    )
    op.execute("ALTER TABLE watchlist_items ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY watchlist_items_owner_only ON watchlist_items
        USING (
            watchlist_id IN (
                SELECT id FROM watchlists
                WHERE user_id = current_setting('app.current_user_id', true)::uuid
            )
        )
        WITH CHECK (
            watchlist_id IN (
                SELECT id FROM watchlists
                WHERE user_id = current_setting('app.current_user_id', true)::uuid
            )
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_stock_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_technical_indicators_stock_id'), table_name='technical_indicators')
    op.drop_index('ix_technical_indicators_stock_date_desc', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_stock_scores_stock_id'), table_name='stock_scores')
    op.drop_table('stock_scores')
    op.drop_index(op.f('ix_realtime_quotes_stock_id'), table_name='realtime_quotes')
    op.drop_index('ix_realtime_quotes_stock_captured_desc', table_name='realtime_quotes')
    op.drop_table('realtime_quotes')
    op.drop_index(op.f('ix_price_history_stock_id'), table_name='price_history')
    op.drop_index('ix_price_history_stock_date_desc', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_data_sync_log_stock_id'), table_name='data_sync_log')
    op.drop_table('data_sync_log')
    op.drop_index(op.f('ix_ai_predictions_stock_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
