"""intraday candle columns

Revision ID: a999c3f519c7
Revises: 9c46159f3bc0
Create Date: 2026-08-14 09:48:50.351057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a999c3f519c7'
down_revision: Union[str, None] = '9c46159f3bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realtime_quotes', sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('realtime_quotes', sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('realtime_quotes', sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('realtime_quotes', sa.Column('accumulated_volume', sa.BigInteger(), nullable=True))
    op.add_column('realtime_quotes', sa.Column('trading_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_realtime_quotes_trading_date'), 'realtime_quotes', ['trading_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_realtime_quotes_trading_date'), table_name='realtime_quotes')
    op.drop_column('realtime_quotes', 'trading_date')
    op.drop_column('realtime_quotes', 'accumulated_volume')
    op.drop_column('realtime_quotes', 'low_price')
    op.drop_column('realtime_quotes', 'high_price')
    op.drop_column('realtime_quotes', 'open_price')
    # ### end Alembic commands ###
