"""market indices

Revision ID: ed0476867449
Revises: be03b3ba799e
Create Date: 2026-08-14 12:06:07.037008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0476867449'
down_revision: Union[str, None] = 'be03b3ba799e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uq_market_indices_code_date')
    )
    op.create_index('ix_market_indices_code_date_desc', 'market_indices', ['code', sa.text('trade_date DESC')], unique=False)
    # ### end Alembic commands ###

    # Bảng tạo sau migration 319166c41e7d nên không nằm trong GRANT ... ON
    # ALL TABLES của migration đó — cấp lại tường minh, giống
    # 03288f241f54_paper_trading_portfolio.py đã làm. IF EXISTS để không vỡ
    # ở môi trường dev chưa tạo role app_backend.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_backend') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON market_indices
                    TO app_backend;
                GRANT USAGE, SELECT ON market_indices_id_seq TO app_backend;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_indices_code_date_desc', table_name='market_indices')
    op.drop_table('market_indices')
    # ### end Alembic commands ###
