"""company fundamentals cache

Revision ID: f4bdb780ca20
Revises: 03288f241f54
Create Date: 2026-08-12 10:04:21.563607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4bdb780ca20'
down_revision: Union[str, None] = '03288f241f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('pe', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('issue_share', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('charter_capital', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('company_profile', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', name='uq_company_fundamentals_stock')
    )
    op.create_index(op.f('ix_company_fundamentals_stock_id'), 'company_fundamentals', ['stock_id'], unique=False)
    # ### end Alembic commands ###

    # KHÔNG bật RLS: đây là dữ liệu công khai của doanh nghiệp, không gắn
    # với người dùng nào (khác portfolios/watchlists).
    #
    # Bảng tạo sau migration 319166c41e7d nên không nằm trong GRANT ... ON
    # ALL TABLES của migration đó — cấp lại tường minh, IF EXISTS để không
    # vỡ ở môi trường dev chưa tạo role.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_backend') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON company_fundamentals TO app_backend;
                GRANT USAGE, SELECT ON company_fundamentals_id_seq TO app_backend;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_fundamentals_stock_id'), table_name='company_fundamentals')
    op.drop_table('company_fundamentals')
    # ### end Alembic commands ###
